### ISSUE TITLE
An example ? 

### ISSUE THREAD

**Issue by melihmucuk** [astrotools/swego#1]
Hi, I want to calculate ephemeris for me, how can I calculate planets locations like below ? 

![mm_astro](https://cloud.githubusercontent.com/assets/3147488/16970835/72b41c46-4e27-11e6-90b1-9feb6d88ac48.gif)

**Comment by dwlnetnl** [comment]
In the read me there is an example at the bottom.

I don't know if you want to use Go to write a program that calculates. If that isn't the case, I suggest you ask on the Swiss Ephemeris mailing list (swisseph@yahoogroups.com).

**Comment by melihmucuk** [comment]
I need just few information, forexample: Sun 4 Tau 27' 48, is it possible with this package ?

**Comment by dwlnetnl** [comment]
As swego is a wrapper around the swisseph C library it tends to be fairly low-level. So it is possible to calculate the position of the Sun, as shown in the example (`xx[0]`). However, you need to format this value yourself which is easy to do.
